version: '3.9'
services:
  database:
    image: postgres:16
    container_name: erp_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: erp_server
    ports:
      - "5432:5432"

  server:
    image: erp_server:latest
    container_name: erp_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    depends_on:
      - database
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8008/handler/v1/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
