version: "3.9"
services:
  api:
    image: erp-server
    container_name: erp-server
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
  db:
    image: postgres:alpine3.18
    container_name: erp-db
    volumes:
      - .docker/postgresql/data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
