---
debug: true
contextTimeout: 5

server:
  port: 8008
  host: '0.0.0.0' # dùng cho docker: localhost sẽ không chạy được trên docker
  #  host: '127.0.0.1'
  env: 'local'
  useRedis: false

services:

database:
  driver: 'postgres'
  #  host: 'host.docker.internal' # dùng cho docker: kết nối vào database trên host
  #  host: 'localhost' # dùng cho local
  host: 'erp_database' # dùng cho docker: kết nối vào container database trên docker
  #  port: 5433 # dùng cho docker: kết nối vào database trên host
  port: 5432 # dùng chạy docker
  username: 'postgres'
  password: 'password'
  name: 'erp_server'
  sslmode: 'disable'
  timezone: 'Asia/Ho_Chi_Minh'
  maxOpenConnections: 10
  maxIdleConnections: 5
  maxConnectionLifetime: 300
jwt:
  secret: 'hgG6T23XD25N'
  accessTokenExpiresIn: 36000000
  refreshTokenExpiresIn: 864000000
logger:
  level: 'debug'
