name: Docker Image CI

on:
  push:
    branches:
      - master
      - deploy

  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  LATEST_TAG: ${{ github.repository }}:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker QEMU
        uses: docker/setup-qemu-action@v2.2.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.LATEST_TAG }}
