name: Docker Image CI
on:
  push:
    branches:
      - master
      - deploy
env:
  REGISTRY: ghcr.io
  TEST_TAG: ${{ github.repository }}:test
  LATEST_TAG: ${{ github.repository }}:latest
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and export Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test Docker image
        run: |
          docker run --rm ${{ env.TEST_TAG }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.LATEST_TAG }}
